### ISSUE TITLE
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in wp-content/plugins/mailgun/includes/wp-mail-api.php on line 369

### ISSUE THREAD

**Issue by kornbed** [mailgun/wordpress-plugin#107]
PHP Deprecation notice with the function base_convert since PHP 7.4
`$boundary = base_convert(uniqid('boundary', true), 10, 36);`

**Comment by uavn** [comment]
fixed here: https://github.com/mailgun/wordpress-plugin/pull/108
