### ISSUE TITLE
Add Custom `From Email` & `From Name`

### ISSUE THREAD

**Issue by KayLeung** [mailgun/wordpress-plugin#11]
Most WP SMTP plugin supports custom `From Email` & `From Name`. It's cool if Mailgun's WP plugin support it officially.

**Comment by pirogoeth** [comment]
Hey @KayLeung, I'm working on this feature today! If you'd like to give it a shot, download the zipball release for [this branch](https://github.com/mailgun/wordpress-plugin/tree/sjohn/from-name-email) and install it into your Wordpress instance :)

All I believe I have left to do is add better documentation to the fields and add the translations, but please let me know if you find any bugs! Thanks!

**Comment by pirogoeth** [comment]
This is done in #32 :)
