### ISSUE TITLE
Make plugin WordPress VIP GO compatible

### ISSUE THREAD

**Issue by SanketChodavadiya** [mailgun/wordpress-plugin#124]
We are using this plugin in few of WP VIP GO project. There is one issue for this environt specific.

[MU plugins](https://github.com/Automattic/vip-go-mu-plugins/) which is default installed to every WP VIP GO project.
There is [filter](https://github.com/Automattic/vip-go-mu-plugins/blob/6baaebe3c8b2d7527ea5820218673b5a9d79bb17/vip-mail.php#L27) added which we have no control to remove and need to override `from email` with higher priority for all project to use custom from email.

This is only possible if there is limited from email address. We have scenario where we don't know what will be from email like in gravity form plugin notification we can set From email.

I have solution for this also in this [PR](https://github.com/mailgun/wordpress-plugin/pull/123).

Please let me know if you need any help.

Thanks.

**Comment by Pavlico** [comment]
Hi @SanketChodavadiya can you help me understand problem more clearly, mb some point by point on how to see your issue.

**Comment by oleksandr-mykhailenko** [comment]
Close issue according to outdated conversation
