### ISSUE TITLE
Problem when coma in Sender name

### ISSUE THREAD

**Issue by crmb** [mailgun/wordpress-plugin#13]
If there is a coma in the sender name, only the second part of the name is used/displayed
Can you reproduce this ? I don't have the issue with another SMTP plugin (Postman SMTP)

Also, please update your plugin on wordpress repo (version compatibiliy). Or remove it.
That's really not serious..

**Comment by pirogoeth** [comment]
Hi there, @crmb! I've updated the plugin on the wordpress repo. Could you let me know if you're still having the comma issue?

**Comment by crmb** [comment]
Hello. sorry for late response. (i am using another plugin (with smtp mode) since.)
I will try ASAP.

**Comment by pirogoeth** [comment]
@crmb No worries, please let me know how it goes.
