### ISSUE TITLE
New update causes site wide fatal errors.

### ISSUE THREAD

**Issue by NightOnFire** [mailgun/wordpress-plugin#132]
Errors include:

AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in [...]/public_html/wp-content/plugins/__mailgun/mailgun.php on line 109\n', referer: https://www.pegcitycarcoop.ca/wp-admin/plugins.php?plugin=__mailgun%2Fmailgun.php

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Return value of Mailgun::load_list_widget() must be an instance of void, none returned in [...]/public_html/wp-content/plugins/mailgun/mailgun.php:498

**Comment by oleksandr-mykhailenko** [comment]
Hello @NightOnFire 
Thank you
The bug was fixed and new version is released
