### ISSUE TITLE
Multipart email issue

### ISSUE THREAD

**Issue by chrisvanpatten** [mailgun/wordpress-plugin#14]
Hey there!

We have some emails being sent from WooCommerce with the `multipart/alternative` content type (the "order processing" email in particular), but the Mailgun plugin seems to ignore that and send it as plaintext… which means that the email comes out looking like unrendered HTML.

I'm fixing this right now by just setting the email to send only as `text/html`, but it might be nice if the plugin supported multipart as well.

Thanks!

**Comment by pirogoeth** [comment]
Hey @chrisvanpatten, this *should* be fixed in the 1.5.1 release. You mind trying to send with `multipart/alternative` again? I'd like to know how it behaves now.

**Comment by omarfilip** [comment]
Hi,

Has this fix been implemented, or has it regressed? In 1.5.8.5, even the "Test Configuration" message comes through as a single line of text:

This is a test email generated by the Mailgun WordPress plugin. If you have received this message, the requested test has succeeded. The method used to send this email was: HTTP API.

Thanks

**Comment by oscarssanchez** [comment]
I don't think this fix has been implemented. A workaround for this is to set manually the body['text'] by setting it with body['html'] and then stripping out the tags of it and making it prettier.

**Comment by michael-picard** [comment]
Hi @pirogoeth, we're at v. 1.7.1 and the mailgun plugin still can not handle woocommerce multipart emails (the text/plain content is html content). `mg_mutate_message_body` works but it's not ideal. it this still on your roadmap ? thanks

**Comment by uavn** [comment]
Will work now

**Comment by devonto** [comment]
Whilst this issue seems to have been resolved and handled, the PHP error being produced on line 316 of wp-mail-api.php still persists.
https://github.com/mailgun/wordpress-plugin/blob/095851a7e2419f58ac67bb3f5b0a0268671a9765/includes/wp-mail-api.php#L316

Can this be removed, assuming it is handled with the code that was added  - or at least add a new `else if ('multipart/alternative' === $content_type)` option on line 314?
