### ISSUE TITLE
wp_mail() : $to parameter being erased by extract()

### ISSUE THREAD

**Issue by Caminyx** [mailgun/wordpress-plugin#149]
PHP version : 7.4
Wordpress version : 6.1.1
Plugin version : 1.8.7

Using Mailgun API.

This error occurred since novembre 8th (or so) since then no email is sent by the website.

After checking mailgun logs, server logs and everything I could error_logging every step of the `wp_mail()` function of this plugin it turns out that the issue sent by mailgun API is that the "to" parameter is missing from the request. It's actually an empty array that is sent...

It seems that the `apply_filters()` on `wp-mail-api.php line 116` isn't returning what it's supposed to and the `extract() line 120` php function is overriding the $to parameter. I can't figure out why this appends.

Until a bug fix is published I commented the lines 116 to 120 of the `wp-mail-api.php`. It seems to work fine without it for now.

Thanks you for your work and support !

**Comment by oleksandr-mykhailenko** [comment]
Hello @Caminyx We are working on it. Plugin will be updated in a 2-3 days.
Thank you

**Comment by oleksandr-mykhailenko** [comment]
Hello @Caminyx We fixed this issue and released a new version. Thank you

**Comment by Caminyx** [comment]
@oleksandr-mykhailenko Thank you for your quick fix and reply, you're amazing. Keep up the good work :)
