### ISSUE TITLE
Plug-in no longer honors the "wp_mail" filter, breaking functionality of other plug-ins.

### ISSUE THREAD

**Issue by pandymic** [mailgun/wordpress-plugin#152]
By removing the call to `apply_filters` in [your plugged wp_mail() override](https://github.com/mailgun/wordpress-plugin/commit/8cc0482a17e4ab3f069342446440be4ade3a4369#diff-6d8ed671e39b35973e37edaa07dc59ee834540457d0d545fcb63a2afb2d0256cL116) you are introducing a breaking change that causes other plug-ins to stop functioning as intended.

Not sure if this was intended to resolve the documented issue with the "$to" variable, but one unintended side-effect is that it also no longer filters any other message data as well, including headers, subject, and message body.

I've confirmed that the "Email Templates" plug-in ceases to function when "Mailgun" is active. Deactivating the plug-in resolves all underlying e-mail formatting issues.

**Comment by oleksandr-mykhailenko** [comment]
Hello @pandymic 
Thank you for noticing this. Plugin was update few minutes ago. So we rollback changes. Thanks
