### ISSUE TITLE
Got unknown Content-Type: multipart/alternative (revisited)

### ISSUE THREAD

**Issue by devonto** [mailgun/wordpress-plugin#157]
Whilst this issue seems to have been resolved and handled, the PHP error being produced on line 316 of wp-mail-api.php still persists.
https://github.com/mailgun/wordpress-plugin/blob/095851a7e2419f58ac67bb3f5b0a0268671a9765/includes/wp-mail-api.php#L316

Can this be removed, assuming it is handled with the code that was added  - or at least add a new `else if ('multipart/alternative' === $content_type)` option on line 314?

_Originally posted by @devonto in https://github.com/mailgun/wordpress-plugin/issues/14#issuecomment-1247798272_

**Comment by oleksandr-mykhailenko** [comment]
Hello,
 this issue was fixed

**Comment by oleksandr-mykhailenko** [comment]
> Thank you, it appears to have solved the problem.

Great, thank you
