### ISSUE TITLE
Version declaration missmatch

### ISSUE THREAD

**Issue by michaelbragg** [mailgun/wordpress-plugin#169]
The `readme.txt` is showing the plugin's stable (latest) version as 1.9.5.

This Git repo and WordPress's SVN are showing the latest tag as 1.9.6 (https://plugins.trac.wordpress.org/browser/mailgun/tags).

We've noticed this as we load the Mailgun plugin via Composer/WPackagist. Which is based on the SVN tags.

Running `wpcli plugin list` shows this issue too as it returns:

```sh
+-----------------------------+----------+------------------------------+---------+
| name                        | status   | update                       | version |
+-----------------------------+----------+------------------------------+---------+
| mailgun                     | inactive | version higher than expected | 1.9.6   |
+-----------------------------+----------+------------------------------+---------+
```

Expected behaviour:

`readme.txt` and SVN tags to be the same.

**Comment by oleksandr-mykhailenko** [comment]
Fixed
Thank you
