### ISSUE TITLE
Broken image, and bad link etiquette

### ISSUE THREAD

**Issue by Garconis** [mailgun/wordpress-plugin#171]
- Your plugin has a logo in the top right, but it’s broken, and has been for over a year: https://www.metsquare.com/wp-content/plugins/mailgun/assets/icon-128×128.png
- Mailgun plugin settings page has links, which should open in a new tab.
- Also, those links have hashes which should auto-scroll to a certain section of the documentation, but nothing auto-scrolls.

**Comment by oleksandr-mykhailenko** [comment]
Thank you, link were fixed. Logo is working

**Comment by Garconis** [comment]
As of 1.9.7, the image has not been fixed. The image now links to `/wp-content/plugins/mailgun/assets/icon-128x128.png` ... but that image doesn't exist.

The links to the documentation that have anchors doesn't stay scrolled. It jumps down for a second, but then jumps back to the top of the Mailgun site.
