### ISSUE TITLE
Plugin "closed" on WordPress.org

### ISSUE THREAD

**Issue by ggwicz** [mailgun/wordpress-plugin#180]
https://wordpress.org/plugins/mailgun/

The plugin listing on WordPress.org is currently unavailable, with a message as follows:

> This plugin has been closed as of 10 July 2024 and is not available for download. This closure is temporary, pending a full review.

This seems likely related to accounts/email addresses not being kept in sync, maybe after the recent acquisition by "Sinch"?

Hopefully this can be resolved, as the `mailgun` slug will **not** be able to be used by any other plugin.

**Comment by oleksandr-mykhailenko** [comment]
Hello @ggwicz 
We are working on that. Thank you. Updates will be soon

**Comment by ggwicz** [comment]
Appreciate the update @oleksandr-mykhailenko!

**Comment by ronilaukkarinen** [comment]
Wondering the same. This affects over 100 sites for us, glad it's a holiday season but in August it would be nice to get it working again. 🙏

**Comment by dmpinder** [comment]
@oleksandr-mykhailenko Has there been any update on this? Like @ronilaukkarinen, we have many client sites which now won't deploy because composer can't install your plugin.

**Comment by oleksandr-mykhailenko** [comment]
@ronilaukkarinen @dmpinder 
I'm frustrated by that news, and did not expect such issues. Currently, I'm working with people, who has an access as plugin authors and try to find any data, that will help to make a progress. According to the policies, we updated code, and from the code perspective we have all needed updates, tags are fresh. (Except changelog, rightnow it's outdated a little bit, but I will make update after plugin review). I hope today, everything will be  updated and plugin will be reviewed by marketplace again.
I'm sos sorry for such problems.

**Comment by dmpinder** [comment]
@oleksandr-mykhailenko Thanks for the reply, and really appreciate your continued efforts!

**Comment by teppokoivula** [comment]
Looks like the plugin is available again.

**Comment by oleksandr-mykhailenko** [comment]
@dmpinder @teppokoivula @ronilaukkarinen 
Plugin is alive again
Changelog will be updated during the day.

**Comment by dmpinder** [comment]
@oleksandr-mykhailenko Thank you! Can you let us know what the issue was?

**Comment by oleksandr-mykhailenko** [comment]
> @oleksandr-mykhailenko Thank you! Can you let us know what the issue was?

Yes, this situation happened because off bounced email in the account owner. Email was not available anymore and plugin was temporary closed. From the code side we got an advice for keeping only last 5 tags for versions. And I kept only last 5 tags, the  most fresh versions. 
So this is the issue.

**Comment by ronilaukkarinen** [comment]
Thanks for the quick fix!
