### ISSUE TITLE
Refusal to update changelog?

### ISSUE THREAD

**Issue by Garconis** [mailgun/wordpress-plugin#182]
You have changelog files, but they haven't been updated with your releases.

https://github.com/mailgun/wordpress-plugin/blob/master/readme.md

https://github.com/mailgun/wordpress-plugin/blob/master/CHANGELOG.md

**Comment by dear-leader** [comment]
Just wanted to chime in to say that I would also appreciate if the changelogs were kept up to date.

**Comment by oleksandr-mykhailenko** [comment]
Hello @Garconis @dear-leader 
Sorry for outdated information. Right now we are working on making plugin available again. After that, changelog will be updated soon

**Comment by Garconis** [comment]
I think the changelog should be updated prior to pushing it out for release? Now all WP installs are getting a notification that an update is available, but nobody knows what changed. See: https://wordpress.org/support/topic/2-0-is-out-but-no-changelog/

**Comment by oleksandr-mykhailenko** [comment]
Update to 2.0.0 was a start point for the future updated. Supporting php 8.2+ and another items. I agree, that this is not a best practice, but we wanted to avoid something like 1.10.0

Anyway, from this day, changelog is updated. Sorry for delays with that
