### ISSUE TITLE
no email fallback

### ISSUE THREAD

**Issue by FreshySitesSupport** [mailgun/wordpress-plugin#188]
During the last major outage a few months ago, emails from forms were simply lost/not sent even after service was restored. Can a simple mail() fallback be implemented here, and/or a log for api connection failures?

**Comment by oleksandr-mykhailenko** [comment]
> During the last major outage a few months ago, emails from forms were simply lost/not sent even after services was restored. Can a simple mail() fallback be implemented here, and/or a log for api connection failures?

Hello, 
thank you for noticing this. We will take it and fix soon

**Comment by FreshySitesSupport** [comment]
Hello Mailgun/wordpress-Plugin,

Thanks for reaching out!

We have received your Help Desk request and a Freshy team member will be in
touch shortly. :)

Thanks so much,
The Freshy Team
[image: Freshy_Logo_RGB.png]

*Please review our **Help Desk Terms of Service*
<https://kb.freshysites.com/article/41-how-our-support-works> *to see what
is supported by our team**, and check out our Knowledge Base
<https://kb.freshysites.com/> for guides and account information!*
{#HS:2670396600-77072#}

**Comment by oleksandr-mykhailenko** [comment]
We implemented fallback in the new version

**Comment by FreshySitesSupport** [comment]
Hello Mailgun/wordpress-Plugin,

Thanks for reaching out!

We have received your Help Desk request and a Freshy team member will be in
touch shortly. :)

Thanks so much,
The Freshy Team
[image: Freshy_Logo_RGB.png]

*Please review our **Help Desk Terms of Service*
<https://kb.freshysites.com/article/41-how-our-support-works> *to see what
is supported by our team**, and check out our Knowledge Base
<https://kb.freshysites.com/> for guides and account information!*
{#HS:2682178298-77540#}

**Comment by FreshySitesSupport** [comment]
Hello Mailgun/wordpress-Plugin,

Thanks for reaching out!

We have received your Help Desk request and a Freshy team member will be in
touch shortly. :)

Thanks so much,
The Freshy Team
[image: Freshy_Logo_RGB.png]

*Please review our **Help Desk Terms of Service*
<https://kb.freshysites.com/article/41-how-our-support-works> *to see what
is supported by our team**, and check out our Knowledge Base
<https://kb.freshysites.com/> for guides and account information!*
{#HS:2682178295-77539#}

**Comment by Garconis** [comment]
When will the new version be in the WordPress.org repo?

**Comment by Garconis** [comment]
When will the new version be in the WordPress.org repo?
