### ISSUE TITLE
Missing includes/mg-api.php

### ISSUE THREAD

**Issue by abdusfauzi** [mailgun/wordpress-plugin#190]
This code return error because it is missing `mg-api.php` file in the plugin package.

https://github.com/mailgun/wordpress-plugin/blob/e0a58638f14d57effc0397a459c239c11a302568/mailgun.php#L91-L93

:)

**Comment by oleksandr-mykhailenko** [comment]
> This code return error because it is missing `mg-api.php` file in the plugin package.
> 
> https://github.com/mailgun/wordpress-plugin/blob/e0a58638f14d57effc0397a459c239c11a302568/mailgun.php#L91-L93
> 
> :)

Hello
Thank you for this point, we will fix

**Comment by oleksandr-mykhailenko** [comment]
Removed this code. Thanks
