### ISSUE TITLE
Latest version not on WordPress.org repo

### ISSUE THREAD

**Issue by Garconis** [mailgun/wordpress-plugin#193]
2.1.1 has been on GitHub for a couple months now, but it's not yet been added to the WordPress.org repo. We really want the email fallback functionality, but was hoping you'd push the WordPress.org version to the latest version that's obtainable on GitHub.

**Comment by oleksandr-mykhailenko** [comment]
Hello
We updated plugin on the Wordpress marketplace. It's up to day. Thank you
