### ISSUE TITLE
Broken update process

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [mailgun/wordpress-plugin#29]
Hey, guys!

Why did you rename the bootstrap file from mailgun.php to Mailgun.php? This breaks the update process: WordPress thinks the original plugin no longer exists and it disables it by default. I see there are only 4 hours since you released the update. Maybe if you're quick enough and rename the file back to mailgun.php you won't bring down 30.000 websites. 

Best regards,
Eusebiu Oprinoiu

**Comment by pirogoeth** [comment]
@EusebiuOprinoiu Hey there, sorry about that. I just picked up this project and was running things through various linters, etc. I've renamed the file and redeployed to the plugins site. Thanks for letting us know!

**Comment by pirogoeth** [comment]
Okay so I cut a new emergency release to fix this and tested the upgrade process from a very old version to the new 1.5.1. It looks good from this side -- any chance you can confirm, @EusebiuOprinoiu?

**Comment by EusebiuOprinoiu** [comment]
I'm glad I could help! Don't forget to rename the file in the Github repo as well. You don't want the same issue at the next update.
As for file naming, it's best to keep everything lowercase. Linux / Unix is case-sensitive and adding uppercase letters to the mix can yield unexpected results on different software stacks.

**Comment by pirogoeth** [comment]
Github is already up to date with SVN and I'm tagging 1.5.1 right now. Much appreciated :)

**Comment by EusebiuOprinoiu** [comment]
Yes, the issue is solved.
WordPress keeps track of active plugins by storing a unique identifying string for each plugin. This string is made by merging the plugin folder name with the name of the bootstrap file. ( "mailgun/mailgun.php" )
As long as this string is unchanged between updates, WordPress knows to reactivate the plugin.

**Comment by pirogoeth** [comment]
Ahhh, understood. Thank you :)

I'll make sure not to break it again! :laughing:
