### ISSUE TITLE
plugin was deactived for two nights in a row now

### ISSUE THREAD

**Issue by KloonDuino** [mailgun/wordpress-plugin#33]
Plugin was deactivated automagicaly for two nights in a row now by my wordpress install.

backend shows message: plugin is deactivated because a file is missing.

(btw: it is annoying to say the least that your change-log is empty. Please keep this updated with stuff that has been done for that release. )

WordPress 4.7
WooCommerce 2.6.9
1.5.1

**Comment by pirogoeth** [comment]
Sorry about that. 1.5.1 release only fixed the issue causing the plugin to get deactivated. There shouldn't be any more disruptions like that. I will update the changelog.

**Comment by pirogoeth** [comment]
Changelog is updated. My apologies.
