### ISSUE TITLE
Undefined property: MailgunAdmin::$hook_suffix

### ISSUE THREAD

**Issue by abdusfauzi** [mailgun/wordpress-plugin#48]
This is a duplicate post from WordPress Support:
https://wordpress.org/support/topic/undefined-property-mailgunadminhook_suffix/

Referring to https://github.com/mailgun/wordpress-plugin/blob/master/includes/admin.php#L309, the `hook_suffix` will not be define, for example when WooCommerce Shop Manager logged into Dashboard. Shop Manager does not have access to `manage_options `, which will prevent defining the `hook_suffix` from line https://github.com/mailgun/wordpress-plugin/blob/master/includes/admin.php#L100.

I would suggest to add the `if (current_user_can('manage_options'))` at `admin_notices` function too.

**Comment by pirogoeth** [comment]
Hey @abdusfauzi, thanks! I'll get this fixed asap.

**Comment by pirogoeth** [comment]
Fixed in the 1.5.8.1 release :)
