### ISSUE TITLE
SMTP host in the Wordpress plug-in is incorrect

### ISSUE THREAD

**Issue by clhammer** [mailgun/wordpress-plugin#5]
On line 72, https://github.com/mailgun/wordpress-plugin/blob/a126fd02b6ac59ac1039cb807e5fd2e44f5508cb/mailgun.php#L72, the SMTP host is specified as smtp.mailgun.net. This should be smtp.mailgun.org instead.

**Comment by pirogoeth** [comment]
Fixed!
