### ISSUE TITLE
Not working on WP 4.8

### ISSUE THREAD

**Issue by andricicezar** [mailgun/wordpress-plugin#57]
Fresh install of WP 4.8 using Docker image.

Where can I check the logs?

When click on `Test configuration`:
```
Mailgun HTTP API Test Failure; status "null"
```

**Comment by Sk8rSeth** [comment]
i am getting the same error on my 4.8 install, which is on a live digitalocean server

**Comment by pirogoeth** [comment]
I can't reproduce locally with a fresh Docker setup on `wordpress:4.8.0-php7.1-apache`. Any chance either of you have firewall rules set up that are preventing communication with the Mailgun HTTP API?

**Comment by GuerrillaCoder** [comment]
Same issue.  I have no outgoing rules set.  What port does it need open?

**Comment by natterstefan** [comment]
Hi guys, any news on this one? I am also not able to send emails from my WordPress instance with Docker on a live digital ocean server using this plugin. Thanks.

**Comment by andricicezar** [comment]
I recommend you to use the plugin WP Mail SMTP, and there, configure 'Other SMTP'.

**Comment by uavn** [comment]
Should now show appropriate error message if plugin can't connect to the host
