### ISSUE TITLE
FEATURE REQUEST: Let users disable override-from

### ISSUE THREAD

**Issue by mitchelldmiller** [mailgun/wordpress-plugin#59]
My latest [Quick Mail Plugin Release](https://github.com/mitchelldmiller/quick-mail-wp-plugin/releases/tag/v3.2.0-beta) checks for Mailgun plugin.

Unfortunately, if `override-from` is enabled, I must subvert your plugin's behavior to let users send email with their own names.

It would be confusing to receive email from an unknown person's name.

Please add an option to let users disable this feature.

**Comment by uavn** [comment]
Seems like already implemented:

![Screenshot from 2020-09-22 22-36-24](https://user-images.githubusercontent.com/315338/94289100-e27ce280-ff60-11ea-88ac-c348595a8bcf.png)
