### ISSUE TITLE
Cannot test config on free plan

### ISSUE THREAD

**Issue by calvintam236** [mailgun/wordpress-plugin#68]
Keep getting "free accounts are for test purposes only" error on the test button while on free plan. Workaround is to upgrade to Unity plan 👎

**Comment by rtpHarry** [comment]
I think you might be hitting the authorised recipients only issue.

With the free account that has no payment details attached you can only use mailgun to send to an authorised address.

1. Click your username in the top right hand corner of the admin panel
1. Choose Account Settings
1. Add an authorised recipient

Or just go to this url https://app.mailgun.com/app/account/authorized.

This feature means you can use it for sending to specified people like your contact forms but not for sending out to random email addresses which I think is a fair limitation. If you put your card details on then I dont think they charge you unless you use all your resources but they will let you send emails out then without this requirement.
