### ISSUE TITLE
FEATURE REQUEST: support for mailgun forward routes

### ISSUE THREAD

**Issue by NZI** [mailgun/wordpress-plugin#69]
After reading through http://mailgun-documentation.readthedocs.io/en/latest/api-routes.html#examples and https://documentation.mailgun.com/en/latest/quickstart-receiving.html#supported-actions-for-routes is it possible to incorporate this in this plugin?

This way the users would not even need to leave their wp-admin to send or receive emails

Just a thought

**Comment by uavn** [comment]
You can manage Routes in MailGun Control Panel (https://help.mailgun.com/hc/en-us/articles/360011355893-How-Do-I-Setup-a-Route-), it make no sense to have this functionality on wordpress plugin.
