### ISSUE TITLE
Version should adhere to Semver rules

### ISSUE THREAD

**Issue by andrejcremoznik** [mailgun/wordpress-plugin#70]
Current version is `1.5.8.5`. This is problematic because tools like Composer rely on semantic versioning when looking up dependencies. I don't know what could possible be the reason for this version number, but I'd like to urge you to drop the 4th digit and adhere to Semver rules.

Semver: https://semver.org/

**Comment by uavn** [comment]
Already solved.
![Screenshot from 2020-09-22 22-25-59](https://user-images.githubusercontent.com/315338/94288996-c37e5080-ff60-11ea-82e3-922a935ba677.png)
