### ISSUE TITLE
Improve error message when admin email not set and test configuration used

### ISSUE THREAD

**Issue by rtpHarry** [mailgun/wordpress-plugin#71]
I have just set up mailgun on a new site im building.

The admin email is still set to `admin@local.test`.

When I set up the Mailgun plugin to use API, click Save, then Test Changes, I get this error popup:

    Mailgun HTTP API Test Failure; status "'to' parameter is not a valid address. please check documentation"

I was bright enough to figure it out but not before I had scanned up and down the page twice looking for this `to` parameter. 

I think you should special case this API reply to give the admin a hint as to what is wrong.

**Comment by masnatacion** [comment]
i have the same issue

**Comment by tleifj** [comment]
If anyone is unclear on this, the admin email is the WordPress admin email which can be found and changed in WordPress at Settings > General > Administration Email Address

**Comment by uavn** [comment]
Error message adjusted
