### ISSUE TITLE
GDPR Compliance 

### ISSUE THREAD

**Issue by Gattermeier** [mailgun/wordpress-plugin#73]
Currently the plugin is lacking compliance with GDPR (double opt in for list subscriptions, etc). 
Is this plugin still maintained, is GDPR compliance on the roadmap, @pirogoeth ?

**Comment by pirogoeth** [comment]
Hi @Gattermeier! Can you provide more information on how the plugin is lacking in compliance with GDPR? As far as I am aware, GDPR does not mention double-opt in at all. 

This plugin is really just a simple wrapper around our API to make integration with Wordpress easier -- it is on our users to ensure that this plugin is used in a manner consistent with GDPR guidelines and our Terms of Service.
