### ISSUE TITLE
Latest plugin silently breaks if configured using constants due to non-documented region requirement

### ISSUE THREAD

**Issue by robbiet480** [mailgun/wordpress-plugin#77]
The latest plugin version published to WordPress.org but not GitHub (versions `1.5.12` and `1.5.12.1`) break compatibility with those using `wp-config.php` to configure the plugin. The latest versions include the ability to specify the region to connect to (yay!) but if the region is not set in the database or, via `wp-config.php` and the undocumented-on-GitHub `MAILGUN_REGION` constant, sending mail will fail. There were no errors in the logs, the only way I was able to find an error was attempting to reset my password which generated the following error: 

```
The email could not be sent.
Possible reason: your host may have disabled the mail() function.
```

**The quick fix for those seeking one** is to define the following constant in your wp-config.php:

```php
define('MAILGUN_REGION', 'us');
```

`eu` and `us` are accepted values.

Mailgun, it would be great if you could:

1. Ensure the latest plugin versions are published here to GitHub before being published on WordPress.org so that the community can test for these kinds of issues.
2. Define a default region if none is set. Alternatively, document the new **required** constant and use `error_log` to notify the user it must be set if it is not already.

**Comment by robbiet480** [comment]
Normally I don't do this, but gonna ping maintainers @pirogoeth and @andrejcremoznik as they are Mailgun employees and this is a pretty urgent issue since it flat out breaks the plugin silently until a fix is released.

**Comment by pirogoeth** [comment]
@robbiet480 We will fix it up today. Thank you for letting us know.

**Comment by pirogoeth** [comment]
@robbiet480 would you like to take a look at #78 and make sure that all bases are covered?

**Comment by robbiet480** [comment]
@pirogoeth Took a very quick look, seems okay (except for the mixed indentation you already mentioned 😛)!

**Comment by aaemnnosttv** [comment]
No default region is currently set. It still requires the constant to be defined or the region to be set in the settings (which aren't there if you're managing via config).

**Comment by pirogoeth** [comment]
@robbiet480 @aaemnnosttv y'all mind taking a look at #80? I've been testing it locally with no region set and things have been working so far.

**Comment by robbiet480** [comment]
@pirogoeth Excellent idea to add an alert in UI about the region, lgtm!

**Comment by pirogoeth** [comment]
Alright y'all, 1.5.13 has been officially released to the world. If you could try it out and confirm that this fixes any issues, I can close out this issue. Thank you for the help!

**Comment by aaemnnosttv** [comment]
Looks good except for in `Mailgun::api_call` where it's missing a fallback for the US region: https://github.com/mailgun/wordpress-plugin/pull/80/files#r210063632.

I haven't tested it yet, but it looks like the changes to `wp_mail` will solve the email deliverability with no region 👍
